/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20MinerReward } from "./ERC20MinerReward";
export type { Lock } from "./Lock";
export type { RcToken } from "./RcToken";
export type { Shipping } from "./Shipping";
