/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ShippingInterface extends Interface {
  getFunction(
    nameOrSignature: "Delivered" | "Shipped" | "Status"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "LogNewAlert"): EventFragment;

  encodeFunctionData(functionFragment: "Delivered", values?: undefined): string;
  encodeFunctionData(functionFragment: "Shipped", values?: undefined): string;
  encodeFunctionData(functionFragment: "Status", values?: undefined): string;

  decodeFunctionResult(functionFragment: "Delivered", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "Shipped", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "Status", data: BytesLike): Result;
}

export namespace LogNewAlertEvent {
  export type InputTuple = [description: string];
  export type OutputTuple = [description: string];
  export interface OutputObject {
    description: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Shipping extends BaseContract {
  connect(runner?: ContractRunner | null): Shipping;
  waitForDeployment(): Promise<this>;

  interface: ShippingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  Delivered: TypedContractMethod<[], [void], "nonpayable">;

  Shipped: TypedContractMethod<[], [void], "nonpayable">;

  Status: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "Delivered"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "Shipped"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "Status"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "LogNewAlert"
  ): TypedContractEvent<
    LogNewAlertEvent.InputTuple,
    LogNewAlertEvent.OutputTuple,
    LogNewAlertEvent.OutputObject
  >;

  filters: {
    "LogNewAlert(string)": TypedContractEvent<
      LogNewAlertEvent.InputTuple,
      LogNewAlertEvent.OutputTuple,
      LogNewAlertEvent.OutputObject
    >;
    LogNewAlert: TypedContractEvent<
      LogNewAlertEvent.InputTuple,
      LogNewAlertEvent.OutputTuple,
      LogNewAlertEvent.OutputObject
    >;
  };
}
